#!/bin/bash
# vpn.sh — Bring up WireGuard VPN and fix routing for Docker networking.
# Invoked from entrypoint.sh when USING_VPN=true.
# Requires NET_ADMIN and NET_RAW Docker capabilities.

set -e

WG_IFACE="${WG_IFACE:-wg0}"
WG_CONFIG="${WG_CONFIG_PATH:-/config/wg0.conf}"

[ -f "$WG_CONFIG" ] || {
    echo "[✗] WireGuard config not found at ${WG_CONFIG}"
    echo "    Mount your .conf file there, e.g.  /path/to/wg0.conf:/config/wg0.conf:ro"
    exit 1
}

# Detect the primary outbound interface (almost always eth0 in Docker, but
# detecting it avoids silent failure on custom network configurations).
ETH_IFACE=$(ip route show default 2>/dev/null | awk 'NR==1 { for(i=1;i<=NF;i++) if($i=="dev") print $(i+1) }')
ETH_IFACE="${ETH_IFACE:-eth0}"
echo "[*] Primary interface: ${ETH_IFACE}"

# Atomic config install with correct permissions.
mkdir -p /etc/wireguard
install -m 600 "$WG_CONFIG" "/etc/wireguard/${WG_IFACE}.conf"

# Docker Desktop on macOS blocks sysctl writes even with NET_ADMIN.
# wg-quick sets net.ipv4.conf.all.src_valid_mark=1 and aborts on EPERM.
# Shim sysctl in PATH so permission errors are silently swallowed.
mkdir -p /tmp/wg-sysctl-shim
printf '#!/bin/sh\n/sbin/sysctl "$@" 2>/dev/null; exit 0\n' > /tmp/wg-sysctl-shim/sysctl
chmod +x /tmp/wg-sysctl-shim/sysctl
export PATH="/tmp/wg-sysctl-shim:$PATH"

# Capture original nameservers BEFORE wg-quick overwrites /etc/resolv.conf with
# only the VPN's DNS.  We restore them afterwards so private domains still resolve.
ORIGINAL_NS=$(grep '^nameserver' /etc/resolv.conf 2>/dev/null | awk '{print $2}')

echo "[*] Starting WireGuard ${WG_IFACE}..."
if ip link show "$WG_IFACE" > /dev/null 2>&1; then
    echo "[*] Interface ${WG_IFACE} already up — skipping wg-quick up."
else
    wg-quick up "$WG_IFACE"
    ip link show "$WG_IFACE" > /dev/null 2>&1 || {
        echo "[✗] Interface ${WG_IFACE} did not come up."
        exit 1
    }
fi
echo "[✓] WireGuard interface ${WG_IFACE} is up."

# Restore original nameservers FIRST so local/private DNS resolves quickly.
# Without this, Docker's 127.0.0.11 nameserver is replaced by VPN DNS only,
# causing timeouts for *.local or private-domain queries.
# Deduplicate in case VPN DNS matches one of the original nameservers.
if [ -n "$ORIGINAL_NS" ]; then
    VPN_NS=$(grep '^nameserver' /etc/resolv.conf 2>/dev/null | awk '{print $2}')
    {
        echo "# Generated by vpn.sh"
        for ns in $ORIGINAL_NS $VPN_NS; do echo "nameserver $ns"; done
    } | awk '!seen[$0]++' > /etc/resolv.conf
    echo "[*] DNS: restored original nameservers before VPN DNS"
fi

# ── Routing fixes for Docker networking ──────────────────────────────────────
#
# With AllowedIPs=0.0.0.0/0, wg-quick captures all traffic through wg0.
# This breaks two things in Docker environments:
#
# 1. OUTBOUND connections to RFC 1918 services (Prowlarr, Booklore, etc.)
#    These should go via ETH_IFACE → Docker host, not through the VPN tunnel.
#    Fix: "to <RFC1918>" routing rules at priority 100 (higher than wg's 32764).
#
# 2. INBOUND port-forwarded connections (dev mode: Vite proxy on the Mac host,
#    or Docker Desktop which routes through a public proxy IP).
#    The container's TCP reply (SYN-ACK) gets routed via wg0 and dropped —
#    TCP handshake never completes.
#    Fix: mark TCP packets that ARRIVE on ETH_IFACE, save to conntrack, restore
#    mark on OUTPUT so reply packets route via the main table → ETH_IFACE.
#    TCP-only: applying this to UDP would corrupt WireGuard's own fwmark
#    (0xca6c), causing WireGuard UDP to misroute via wg0 → tunnel breaks.

# Fix 1: RFC 1918 outbound traffic goes directly via ETH_IFACE (main table).
for net in 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16; do
    ip rule add to "$net" lookup main priority 100 2>/dev/null || true
done
echo "[*] Routing: RFC 1918 → main table (priority 100)"

# Fix 2: TCP reply traffic for inbound connections stays on ETH_IFACE.
# Steps: SET mark 0x80 on arriving TCP → SAVE to conntrack → RESTORE on OUTPUT.
# The SET step MUST precede SAVE: CONNMARK --save-mark copies the packet mark,
# so without SET the saved value would be 0, not 0x80.
# Use -C (check) before -A (append) so re-running vpn.sh doesn't
# duplicate rules and corrupt routing (e.g. on container restart without full teardown).
iptables -t mangle -C PREROUTING -i "$ETH_IFACE" -p tcp -j MARK --set-xmark 0x80/0x80 2>/dev/null || \
    iptables -t mangle -A PREROUTING -i "$ETH_IFACE" -p tcp -j MARK --set-xmark 0x80/0x80
iptables -t mangle -C PREROUTING -i "$ETH_IFACE" -p tcp -j CONNMARK --save-mark --nfmask 0x80 --ctmask 0x80 2>/dev/null || \
    iptables -t mangle -A PREROUTING -i "$ETH_IFACE" -p tcp -j CONNMARK --save-mark --nfmask 0x80 --ctmask 0x80
iptables -t mangle -C OUTPUT                      -p tcp -j CONNMARK --restore-mark --nfmask 0x80 --ctmask 0x80 2>/dev/null || \
    iptables -t mangle -A OUTPUT                      -p tcp -j CONNMARK --restore-mark --nfmask 0x80 --ctmask 0x80
ip rule add fwmark 0x80 lookup main priority 50 2>/dev/null || true
echo "[*] Routing: TCP reply traffic → main table via connmark (priority 50)"

# Verify external connectivity through the tunnel.
VPN_IP=$(curl -s --max-time 15 https://api.ipify.org 2>/dev/null || true)
if [ -n "$VPN_IP" ]; then
    echo "[✓] WireGuard active. Outbound IP: ${VPN_IP}"
else
    echo "[!] WireGuard interface is up but could not verify outbound IP."
    echo "    Traffic may not be routing through the VPN yet — the first"
    echo "    handshake may still be in progress. Check with: wg show ${WG_IFACE}"
fi
